deploy:
  branch:
    server: backdrop1.examples.zen.ci
    username: zenci
    dir: '{home}/github/{repo_owner}/{repo_name}/{branch}'
    env_vars:
      docroot: '{home}/domains/backdrop1.examples.zen.ci'
      domain: 'backdrop1.examples.zen.ci'
      database_name: zenci_backdrop1
      database_user: zenci_backdrop1
      database_pass: DBPASSWORD
      account_user: admin@zen.ci
      account_mail: admin@zen.ci
      account_pass: REPLACE_WITH_ADMIN_PASSWORD
      site_mail: noreply@zen.ci
      site_name: 'backdrop-starter-kit example 1.'
    scripts:
      init: '{deploy_dir}/scripts/deploy_init.sh'
